### ISSUE TITLE
projects/links section

### ISSUE THREAD

**Issue by mikerspencer** [CodingEDI/CodingEDI.github.io#6]
* Arfon
   * https://joss.theoj.org/
* Kirstie
   * The book: https://the-turing-way.netlify.com
   * Github repository: https://github.com/alan-turing-institute/the-turing-way
   * Commuity co-working calls: https://the-turing-way.netlify.app/community-handbook/coworking.html
   * Slack: https://tinyurl.com/jointuringwayslack
   * Twitter: https://twitter.com/turingway
   * Mailing list: https://tinyletter.com/TuringWay
* Saber
   * https://inputapp.io
* John
   * ETL Helper: https://pypi.org/project/etlhelper/
   * BGS GitHub: https://github.com/BritishGeologicalSurvey
   * UKGEOS Glasgow (will feature in talk): https://ukgeos.ac.uk/observatories/glasgow
* Sian
   * Data maturity framework: https://www.dataorchard.org.uk/resources/data-maturity-framework

**Comment by GregSutcliffe** [comment]
I'm unclear where this should go @mikerspencer  - the site is singlepage, so this will look pretty messy if we add it to the main area. I can add buttons to each speaker's popup, but beyond about 4 it gets ugly (you can test the current ones right now, eg 2 on Arfon's page).

I could just add them to the markdown for the speaker ... would that do?

**Comment by mikerspencer** [comment]
They came through with each speaker - so let's go for easiest and add them to the markdown for each speaker.
