### ISSUE TITLE
Sian Basker

### ISSUE THREAD

**Issue by mikerspencer** [CodingEDI/CodingEDI.github.io#7]
Bio: Co Chief Exec at [Data Orchard](https://www.dataorchard.org.uk/). Data maturity, analysis, digital tech, inclusion, equality, social change, fiendish scrabble player, singer, curious explorer.

https://twitter.com/sianbasker

Links: 
Data maturity framework: https://www.dataorchard.org.uk/resources/data-maturity-framework

![SianBasker](https://user-images.githubusercontent.com/7642073/120461667-18952080-c392-11eb-8e2f-19eb05641253.jpg)

**Comment by GregSutcliffe** [comment]
I assume the talk details are still TBA?

**Comment by mikerspencer** [comment]
Yeah, plan is to speak to Sian today.

**Comment by mikerspencer** [comment]
Here's the deets from Sian:


Title
Data Maturity – A Fruitful Journey for the Not-for-Profit Sector
OR
Data Maturity – A Fruitful Journey towards Data4Good in the Not-for-Profit Sector

Abstract 
Data Orchard works collaboratively with others to build the data capabilities of the not-for-profit sector.  Since 2015 they have researching data maturity and openly sharing their knowledge and resources. Their free online data maturity assessment tool launched in October 2019 and has been used by hundreds of non-governmental, public sector, universities and commercial organisations. In this session, Sian Basker will reflect on how collaboration and openness have created strong roots and are beginning to produce rich fruits in knowledge and learning for advancing the sector.

Biography
Sian is a social entrepreneur passionate about the role of data for helping non-profit organisations achieve greater impact. Since 2015 she has led Data Orchard’s pioneering national research on data maturity in the non-profit sector. Sian has held trustee and senior roles in digital strategy and business development with local, national, and international charities alongside a couple of stints in academic research. Her career roots are in digital access and inclusion, digital strategy and impact measurement. Sian has an MSc in Data Science and Analytics and a BSC in ‘Mathematics and Science & Technology Policy’. When not championing data4good she marvels at how the sum is greater than it’s parts in her community choir, and enjoys the fun and games of parenting teenagers. 

Links
https://www.dataorchard.org.uk/tools-and-resources
https://www.dataorchard.org.uk/data-maturity-assessment-tool
https://www.dataorchard.org.uk/what-is-data-maturity
https://www.dataorchard.org.uk/news
https://www.dataorchard.org.uk/our-work
Twitter
@Data_Orchard
@sianbasker
LinkedIn
https://www.linkedin.com/in/sian-basker-4653baa/
