### ISSUE TITLE
David Calder

### ISSUE THREAD

**Issue by mikerspencer** [CodingEDI/CodingEDI.github.io#8]
Bio: Principal Information Analyst at Public Health Scotland. Passionate about statistics and statistical programming. Putting customers at the heart of all statistical outputs.

Links: 
* Github: https://github.com/Public-Health-Scotland
* Digital strategy: https://publichealthscotland.scot/news/2021/june/launch-of-new-digital-and-data-strategy-for-public-health-scotland/

![DavidCalder](https://user-images.githubusercontent.com/7642073/120466929-8728ad00-c397-11eb-92f4-f6246d0e2d16.jpeg)

**Comment by GregSutcliffe** [comment]
Talk TBA, leaving open

**Comment by mikerspencer** [comment]
Awaiting title...

Bio
Principal Information Analyst at Public Health Scotland leading the Transforming Publishing Team. Developing Reproducible Analytical Pipelines using open source software and putting customers at the heart of all data products.


Abstract
Public Health Scotland is the primary producer of official statistics for the NHS in Scotland and has around 200 public releases of data each year. Production of these statistics using proprietary software can be time consuming, resource-intensive and cumbersome. Reproducible Analytical Pipelines utilises open source tools and combines data science best practice and principles to effectively automate these processes to increase auditability, efficiency and quality. These RAP projects are also produced in the open so there is increased transparency and trust.

**Comment by mikerspencer** [comment]
and title:

Using open source software to develop Reproducible Analytical Pipelines to improve quality and trust in official statistics
